"""
Raksha Vision Core — Rule Engine v2
=====================================
Primary behavioral intelligence decision system.

Every alert is generated by an evaluated, named rule.
No alert fires without: condition check → temporal gate → cooldown.

PRIORITY ORDER (highest wins per entity context):
  CRIME=5 > CROWD/SECURITY=4 > ANOMALY=3 > BEHAVIOR=2 > BUSINESS=1 > SYSTEM=0

Best-match selector runs per-frame inside evaluate_all():
  • One winner per person   (highest priority + score)
  • One winner per pair     (highest priority + score)
  • One winner per scene category (CRIME, SECURITY, CROWD, etc.)

Pipeline:
    extract_features(active, mature, W, H, now) → SceneFeature
    evaluate_all(scene, now)                     → List[dict]

Debug: RAKSHA_DEBUG_RULES=1 → per-rule PASS/FAIL + suppression trace
"""
from __future__ import annotations

import logging
import math
import os
import time
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Dict, List, Optional

if TYPE_CHECKING:
    from core_backend.camera_service.manager import FrameAnalyser, PersonTrack

log = logging.getLogger("raksha.rules")
_DEBUG = os.environ.get("RAKSHA_DEBUG_RULES") == "1"


# ─── Feature dataclasses ──────────────────────────────────────────────────────

@dataclass
class PersonFeature:
    uid: str
    state: str
    velocity: float
    chaos: float
    motion_class: str            # "LOW" / "MEDIUM" / "HIGH"
    dwell: float
    displacement_5s: float
    displacement_30s: float
    in_restricted: bool
    in_checkout: bool
    last_x: int
    last_y: int
    burst_count: int
    direction_changes_30s: int
    direction_changes_20s: int
    direction_changes_15s: int
    motion_variance_5s: float
    _track: object


@dataclass
class PairFeature:
    a: PersonFeature
    b: PersonFeature
    pair_key: str
    distance: float
    va: float
    vb: float
    v_max: float
    v_sum: float
    v_min: float
    approaching: bool
    closing_speed: float
    interaction_active: bool
    interaction_duration: float
    same_direction: bool
    contact: bool
    chaos_max: float
    burst_max: int
    mc_a: str
    mc_b: str
    intent_score: float
    normal_blocked: bool
    overlapping: bool
    _ix: object


@dataclass
class SceneFeature:
    count: int
    mature_count: int
    running_count: int
    mobile_count: int
    avg_velocity: float
    cluster_spread: float
    persons: List[PersonFeature] = field(default_factory=list)
    pairs: List[PairFeature] = field(default_factory=list)
    after_hours: bool = False
    W: int = 640
    H: int = 360


# ─── Debug helper ──────────────────────────────────────────────────────────────

def _dbg(rule_id: str, passed: bool, details: str = "") -> None:
    if _DEBUG:
        log.debug("[RULE %-12s] %s  %s", rule_id, "PASS" if passed else "FAIL", details)


# ─── Rule Engine ──────────────────────────────────────────────────────────────

class RuleEngine:
    """
    Primary decision system wired into FrameAnalyser.process().

    Replaces all old _pair_rules, _person_rules, _scene_rules,
    _escalation_engine, _group_fight_detection, _beh_*_rules, _after_hours.

    Kept outside: _entry_crossing, _anomaly_rules, _sys_rules, Re-ID.
    """

    # Priority constants — higher number = wins best-match selection
    _CATEGORY_PRIORITY: Dict[str, int] = {
        "CRIME": 5, "CROWD": 4, "SECURITY": 4,
        "ANOMALY": 3, "BEHAVIOR": 2, "BUSINESS": 1, "SYSTEM": 0,
    }
    _SEVERITY_SCORE: Dict[str, int] = {
        "CRITICAL": 4, "HIGH": 3, "MEDIUM": 2, "LOW": 1,
    }

    def __init__(self, analyser: "FrameAnalyser") -> None:
        self._a = analyser

    # ── Feature extraction ────────────────────────────────────────────────────

    def extract_features(self, active: list, mature: list,
                         W: int, H: int, now: float) -> SceneFeature:
        a = self._a

        persons: List[PersonFeature] = []
        for t in mature:
            vel = t.smooth_velocity(0.4)
            mc  = a._classify_motion(vel)
            cx, cy = t.last_pos()
            rx1, ry1, rx2, ry2 = a.restricted_zone
            cx1, cy1, cx2, cy2 = a.checkout_zone
            in_res = (rx1 * W <= cx <= rx2 * W) and (ry1 * H <= cy <= ry2 * H)
            in_chk = (cx1 * W <= cx <= cx2 * W) and (cy1 * H <= cy <= cy2 * H)

            persons.append(PersonFeature(
                uid=t.uid,
                state=t.state.value,
                velocity=vel,
                chaos=a._chaos_score(t, 2.0),
                motion_class=mc,
                dwell=t.dwell_sec(),
                displacement_5s=t.displacement_px(5.0),
                displacement_30s=t.displacement_px(30.0),
                in_restricted=in_res,
                in_checkout=in_chk,
                last_x=cx, last_y=cy,
                burst_count=a._motion_burst_count(t, 1.5),
                direction_changes_30s=a._direction_changes(t, 30.0),
                direction_changes_20s=a._direction_changes(t, 20.0),
                direction_changes_15s=a._direction_changes(t, 15.0),
                motion_variance_5s=a._motion_variance(t, 5.0),
                _track=t,
            ))

        pairs: List[PairFeature] = []
        for i in range(len(persons)):
            for j in range(i + 1, len(persons)):
                pf_a, pf_b = persons[i], persons[j]
                ta, tb = pf_a._track, pf_b._track
                pk = f"{min(ta.uid, tb.uid)}:{max(ta.uid, tb.uid)}"
                ix = a._compute_interaction(ta, tb, pk, now)
                dist = ix.distance
                va, vb = pf_a.velocity, pf_b.velocity

                overlapping = False
                if ta.bboxes and tb.bboxes:
                    ax1, ay1, aw, ah = ta.bboxes[-1]
                    bx1, by1, bw, bh = tb.bboxes[-1]
                    overlapping = not (ax1 + aw < bx1 or bx1 + bw < ax1 or
                                       ay1 + ah < by1 or by1 + bh < ay1)

                pairs.append(PairFeature(
                    a=pf_a, b=pf_b, pair_key=pk,
                    distance=dist,
                    va=va, vb=vb,
                    v_max=max(va, vb), v_sum=va + vb, v_min=min(va, vb),
                    approaching=ix.approaching,
                    closing_speed=ix.closing_speed,
                    interaction_active=ix.active,
                    interaction_duration=ix.duration,
                    same_direction=a._same_direction(ta, tb),
                    contact=a._has_contact(ta, tb, dist),
                    chaos_max=max(pf_a.chaos, pf_b.chaos),
                    burst_max=max(pf_a.burst_count, pf_b.burst_count),
                    mc_a=pf_a.motion_class, mc_b=pf_b.motion_class,
                    intent_score=a._assault_intent_score(ta, tb, ix),
                    normal_blocked=a._normal_behavior_block(ta, tb, va, vb, dist, ix),
                    overlapping=overlapping,
                    _ix=ix,
                ))

        velocities = [t.smooth_velocity(0.4) for t in active]
        avg_vel = sum(velocities) / len(velocities) if velocities else 0.0

        cluster_s = 9999.0
        if len(active) >= 2:
            positions = [t.last_pos() for t in active]
            xs, ys = zip(*positions)
            cluster_s = float(max(max(xs) - min(xs), max(ys) - min(ys)))

        h = int(time.strftime("%H"))
        return SceneFeature(
            count=len(active),
            mature_count=len(mature),
            running_count=sum(1 for t in active if t.state.value in ("RUNNING", "FLEEING")),
            mobile_count=sum(1 for t in active if t.is_mobile()),
            avg_velocity=avg_vel,
            cluster_spread=cluster_s,
            persons=persons,
            pairs=pairs,
            after_hours=(h >= 22 or h < 7),
            W=W, H=H,
        )

    # ── Internal fire helper ───────────────────────────────────────────────────

    def _fire_rule(self, rule_id: str, now: float,
                   category: str, severity: str,
                   name: str, desc: str, trigger_str: str,
                   action: str, reasons: list,
                   entity_id: str, score: int,
                   extra: Optional[dict] = None) -> Optional[dict]:
        """
        Enforce cooldown + rate limit, then emit the alert dict.
        No hidden confidence gate — the rule's conditions ARE the gate.

        entity_id="GROUP" → scene-level cooldown keyed on rule_id.
        entity_id=<uid>   → per-person cooldown keyed on rule_id:uid.
        extra              → merged into the event dict (used for _pair_key tagging).
        """
        a = self._a
        cd_key = rule_id if entity_id == "GROUP" else f"{rule_id}:{entity_id}"
        if now - a.fired.get(cd_key, 0) < a.CD.get(rule_id, 60):
            return None
        if not a._rate_ok(severity, now):
            return None
        a.fired[cd_key] = now
        ev = {
            "type":        "ALERT",
            "event_id":    f"EVT-{int(now * 1000) % 100_000_000}",
            "rule_id":     rule_id,
            "rule_name":   name,
            "category":    category,
            "severity":    severity,
            "risk_score":  max(1, min(99, score)),
            "person_id":   entity_id,
            "camera_id":   a.cam_id,
            "camera_name": a.cam_name,
            "zone":        a.zone,
            "description": desc,
            "trigger":     trigger_str,
            "action":      action,
            "reasons":     reasons,
            "timestamp":   time.strftime("%Y-%m-%dT%H:%M:%S"),
        }
        if extra:
            ev.update(extra)
        return ev

    # ── Best-match selector ────────────────────────────────────────────────────

    def _select_best_per_entity(self, events: List[dict]) -> List[dict]:
        """
        For each entity context, keep only the highest-priority/score rule.

        Groups:
          • Pair events   — tagged _pair_key in event dict; one winner per pair
          • Person events — person_id = track uid; one winner per person
          • Scene events  — person_id = "GROUP" / "SYSTEM"; one winner per category

        Within each group: winner = (priority DESC, severity DESC, risk_score DESC).
        RAKSHA_DEBUG_RULES=1 logs suppressed rules per entity.
        """
        def _sort_key(e: dict):
            return (
                self._CATEGORY_PRIORITY.get(e.get("category", ""), 0),
                self._SEVERITY_SCORE.get(e.get("severity", "LOW"), 0),
                e.get("risk_score", 0),
            )

        pair_buckets:   Dict[str, List[dict]] = {}
        person_buckets: Dict[str, List[dict]] = {}
        scene_list:     List[dict]             = []

        for e in events:
            pk  = e.get("_pair_key")
            pid = e.get("person_id", "GROUP")
            if pk:
                pair_buckets.setdefault(pk, []).append(e)
            elif pid not in ("GROUP", "SYSTEM"):
                person_buckets.setdefault(pid, []).append(e)
            else:
                scene_list.append(e)

        winners: List[dict] = []

        # One winner per person
        for uid, evs in person_buckets.items():
            best = max(evs, key=_sort_key)
            winners.append(best)
            if _DEBUG and len(evs) > 1:
                log.debug("[BEST-MATCH] person=%s winner=%s suppressed=%s",
                          uid, best["rule_id"],
                          [e["rule_id"] for e in evs if e is not best])

        # One winner per pair
        for pk, evs in pair_buckets.items():
            best = max(evs, key=_sort_key)
            winners.append(best)
            if _DEBUG and len(evs) > 1:
                log.debug("[BEST-MATCH] pair=%s winner=%s suppressed=%s",
                          pk, best["rule_id"],
                          [e["rule_id"] for e in evs if e is not best])

        # Scene: best per category (CRIME, SECURITY, CROWD each get one slot)
        seen_cats: set = set()
        for e in sorted(scene_list, key=_sort_key, reverse=True):
            cat = e.get("category", "")
            if cat not in seen_cats:
                seen_cats.add(cat)
                winners.append(e)
            elif _DEBUG:
                log.debug("[BEST-MATCH] scene cat=%s suppressed=%s",
                          cat, e.get("rule_id"))

        return winners

    # ── Main evaluate loop ─────────────────────────────────────────────────────

    def evaluate_all(self, scene: SceneFeature, now: float) -> List[dict]:
        events: List[dict] = []

        # ── Pair-level rules ──────────────────────────────────────────────────
        for pair in scene.pairs:
            events.extend(self._eval_crm001(pair, scene, now))
            events.extend(self._eval_crm002(pair, scene, now))
            events.extend(self._eval_crm003(pair, scene, now))
            events.extend(self._eval_crm004(pair, scene, now))
            events.extend(self._eval_crm007(pair, scene, now))
            events.extend(self._eval_crm008(pair, scene, now))
            events.extend(self._eval_crm009(pair, scene, now))
            events.extend(self._eval_sec014(pair, scene, now))

        # ── Person-level rules ────────────────────────────────────────────────
        for person in scene.persons:
            for fn in (
                self._eval_crm013, self._eval_crm015, self._eval_crm016,
                self._eval_sec001, self._eval_sec002, self._eval_sec003,
                self._eval_sec005, self._eval_sec006, self._eval_sec008,
                self._eval_beh001, self._eval_beh003, self._eval_beh010,
                self._eval_beh012, self._eval_beh017, self._eval_beh018,
                self._eval_beh022, self._eval_beh027,
                self._eval_biz003, self._eval_crw004,
            ):
                ev = fn(person, now)
                if ev:
                    events.append(ev)

        # ── Scene-level rules ─────────────────────────────────────────────────
        for fn in (
            self._eval_crm010, self._eval_crm011, self._eval_crm014,
            self._eval_crw001, self._eval_sec009, self._eval_sec011,
            self._eval_sec012, self._eval_beh026, self._eval_biz004,
        ):
            ev = fn(scene, now)
            if ev:
                events.append(ev)

        events = [e for e in events if e is not None]

        if _DEBUG:
            log.debug("[FRAME] %d raw events before best-match", len(events))

        # ── Best-match: one winner per entity context ─────────────────────────
        return self._select_best_per_entity(events)

    def reset(self) -> None:
        pass

    # ══════════════════════════════════════════════════════════════════════════
    # PAIR-LEVEL EVALUATORS
    # ══════════════════════════════════════════════════════════════════════════

    def _eval_crm001(self, pair: PairFeature, scene: SceneFeature, now: float) -> List[dict]:
        """CRM-001: Chain / Bag Snatching — one FLEEING, other IDLE/STANDING"""
        a = self._a
        tk = f"CRM-001:{pair.pair_key}"

        if pair.distance < a.DIST_SNATCH and pair.interaction_active:
            fast_is_a = pair.va > pair.vb
            fast_pf   = pair.a if fast_is_a else pair.b
            slow_pf   = pair.b if fast_is_a else pair.a
            fast_t    = fast_pf._track

            cond = (
                fast_t.state.value in ("FLEEING", "RUNNING")
                and fast_t.smooth_velocity(0.6) >= a.VEL_FLEE
                and slow_pf.state in ("WALKING", "STANDING", "IDLE")
            )
            _dbg("CRM-001", cond,
                 f"d={int(pair.distance)}px fast_v={int(fast_pf.velocity)} slow={slow_pf.state}")
            if cond:
                if a._tgate(a.scene_triggers, tk, now, gap_tol=0.4):
                    ev = self._fire_rule(
                        "CRM-001", now, "CRIME", "CRITICAL",
                        "Chain / Bag Snatching Detected",
                        "Person in close contact then immediately fled — chain/bag snatch.",
                        f"d={int(pair.distance)}px fast={int(fast_pf.velocity)}px/s slow={slow_pf.state}",
                        "Alert ALL exits. Aid victim. Call police.",
                        ["snatching", "chain-snatch", "robbery"],
                        "GROUP", 94,
                        extra={"_pair_key": pair.pair_key},
                    )
                    return [ev] if ev else []
            else:
                a._tgate_reset(a.scene_triggers, tk)
        else:
            a._tgate_reset(a.scene_triggers, tk)
        return []

    def _eval_crm002(self, pair: PairFeature, scene: SceneFeature, now: float) -> List[dict]:
        """
        CRM-002: Physical Assault — ALL violence signals must be present simultaneously.

        Blocked immediately when pair is demonstrably non-violent (normal_blocked).
        Requires: sustained interaction + high velocity + approaching + (contact OR
        repeated strike bursts) + chaotic motion + assault intent ≥ threshold.
        """
        a = self._a
        tk = f"CRM-002:{pair.pair_key}"

        if pair.normal_blocked:
            a._tgate_reset(a.scene_triggers, tk)
            _dbg("CRM-002", False,
                 f"NORMAL_BLOCKED d={int(pair.distance)}px "
                 f"mc={pair.mc_a}/{pair.mc_b} chaos={pair.chaos_max:.2f}")
            return []

        cond = (
            pair.interaction_active
            and pair.distance < a.DIST_FIGHT * 1.5
            and pair.v_max > a.VEL_RUN * 0.6
            and pair.v_sum > a.VEL_WALK * 0.8
            and pair.approaching
            and (pair.contact or pair.burst_max >= 2)
            and pair.chaos_max >= 0.22
            and pair.intent_score >= a.ASSAULT_INTENT_THRESHOLD
        )
        _dbg("CRM-002", cond,
             f"d={int(pair.distance)}px v_max={int(pair.v_max)} "
             f"contact={pair.contact} bursts={pair.burst_max} "
             f"chaos={pair.chaos_max:.2f} intent={pair.intent_score:.2f} "
             f"approach={pair.approaching} interact={pair.interaction_active}")
        if cond:
            if a._tgate(a.scene_triggers, tk, now, gap_tol=0.4):
                score = int(min(99, pair.intent_score * 110))
                ev = self._fire_rule(
                    "CRM-002", now, "CRIME", "CRITICAL",
                    "Physical Assault Detected",
                    "Rule engine confirmed: all violence signals present simultaneously.",
                    (f"d={int(pair.distance)}px v_max={int(pair.v_max)}px/s "
                     f"intent={pair.intent_score:.2f} chaos={pair.chaos_max:.2f} "
                     f"contact={pair.contact} bursts={pair.burst_max}"),
                    "Deploy security immediately. Call police. Aid injured.",
                    ["assault", "violence", "fight"],
                    "GROUP", score,
                    extra={"_pair_key": pair.pair_key},
                )
                return [ev] if ev else []
        else:
            a._tgate_reset(a.scene_triggers, tk)
        return []

    def _eval_crm003(self, pair: PairFeature, scene: SceneFeature, now: float) -> List[dict]:
        """CRM-003: Robbery / Mugging — active aggressor, stationary victim"""
        a = self._a
        tk = f"CRM-003:{pair.pair_key}"

        cond_basic = (
            pair.interaction_active
            and pair.distance < a.DIST_SNATCH * 1.2
            and pair.v_max > a.VEL_RUN * 0.8
            and pair.v_min < a.VEL_WALK * 0.5
        )
        if cond_basic:
            fast_t = pair.a._track if pair.va > pair.vb else pair.b._track
            cond   = fast_t.state.value in ("RUNNING", "WALKING")
            _dbg("CRM-003", cond,
                 f"d={int(pair.distance)}px v_max={int(pair.v_max)} v_min={int(pair.v_min)}")
            if cond:
                if a._tgate(a.scene_triggers, tk, now, gap_tol=0.5):
                    ev = self._fire_rule(
                        "CRM-003", now, "CRIME", "CRITICAL",
                        "Robbery / Mugging Detected",
                        "Active aggressor engaging stationary victim.",
                        f"d={int(pair.distance)}px aggressor={int(pair.v_max)}px/s victim≈IDLE",
                        "Alert security. Call police.",
                        ["robbery", "mugging"],
                        "GROUP", 88,
                        extra={"_pair_key": pair.pair_key},
                    )
                    return [ev] if ev else []
            else:
                a._tgate_reset(a.scene_triggers, tk)
        else:
            a._tgate_reset(a.scene_triggers, tk)
        return []

    def _eval_crm004(self, pair: PairFeature, scene: SceneFeature, now: float) -> List[dict]:
        """CRM-004: Pickpocketing — very close, slow, sustained contact (≥6s)"""
        a = self._a
        tk     = f"CRM-004:{pair.pair_key}"
        d_55px = int(55 * scene.W / 640.0)

        cond = (
            pair.interaction_active
            and pair.distance < d_55px
            and pair.v_sum < a.VEL_WALK * 2.5
            and pair.a.state not in ("FLEEING", "RUNNING", "FALLEN")
            and pair.b.state not in ("FLEEING", "RUNNING", "FALLEN")
            and not pair.a.in_checkout
        )
        _dbg("CRM-004", cond,
             f"d={int(pair.distance)}px/{d_55px} v_sum={int(pair.v_sum)} chk={pair.a.in_checkout}")
        if cond:
            if a._tgate(a.scene_triggers, tk, now, gap_tol=1.0):
                ev = self._fire_rule(
                    "CRM-004", now, "CRIME", "HIGH",
                    "Possible Pickpocketing",
                    "Two persons in very close sustained standing contact (not at checkout).",
                    f"d={int(pair.distance)}px v_sum={int(pair.v_sum)}px/s sustained ≥6s",
                    "Alert plainclothes staff. Review footage.",
                    ["pickpocket", "theft"],
                    "GROUP", 70,
                    extra={"_pair_key": pair.pair_key},
                )
                return [ev] if ev else []
        else:
            a._tgate_reset(a.scene_triggers, tk)
        return []

    def _eval_crm007(self, pair: PairFeature, scene: SceneFeature, now: float) -> List[dict]:
        """CRM-007: Stalking / Following (≥10s sustained)"""
        a = self._a
        tk = f"CRM-007:{pair.pair_key}"

        cond = (
            a.DIST_FOLLOW * 0.3 < pair.distance < a.DIST_FOLLOW
            and pair.a._track.is_mobile()
            and pair.b._track.is_mobile()
            and pair.same_direction
        )
        _dbg("CRM-007", cond,
             f"d={int(pair.distance)}px same_dir={pair.same_direction}")
        if cond:
            if a._tgate(a.scene_triggers, tk, now, gap_tol=2.0):
                ev = self._fire_rule(
                    "CRM-007", now, "CRIME", "HIGH",
                    "Stalking / Following",
                    "Person consistently following another at fixed distance.",
                    f"d={int(pair.distance)}px same direction, both mobile",
                    "Alert security. Warn potential victim discreetly.",
                    ["stalking", "following", "harassment"],
                    "GROUP", 68,
                    extra={"_pair_key": pair.pair_key},
                )
                return [ev] if ev else []
        else:
            a._tgate_reset(a.scene_triggers, tk)
        return []

    def _eval_crm008(self, pair: PairFeature, scene: SceneFeature, now: float) -> List[dict]:
        """CRM-008: Kidnapping / Forcible Removal — two running fast, same direction, close"""
        a = self._a
        tk = f"CRM-008:{pair.pair_key}"

        cond = (
            pair.interaction_active
            and pair.distance < a.DIST_SNATCH
            and pair.v_sum > a.VEL_RUN * 2.0
            and pair.same_direction
            and pair.a.state in ("RUNNING", "FLEEING")
            and pair.b.state in ("RUNNING", "FLEEING")
            and not pair.normal_blocked
        )
        _dbg("CRM-008", cond,
             f"d={int(pair.distance)}px v_sum={int(pair.v_sum)} same_dir={pair.same_direction}")
        if cond:
            if a._tgate(a.scene_triggers, tk, now, gap_tol=0.5):
                ev = self._fire_rule(
                    "CRM-008", now, "CRIME", "CRITICAL",
                    "Kidnapping / Forcible Removal",
                    "Two persons running at high speed in same direction — possible abduction.",
                    f"d={int(pair.distance)}px v_sum={int(pair.v_sum)}px/s same_dir",
                    "IMMEDIATE police alert. Block exits if safe. Do not lose visual.",
                    ["kidnapping", "abduction", "forcible-removal"],
                    "GROUP", 92,
                    extra={"_pair_key": pair.pair_key},
                )
                return [ev] if ev else []
        else:
            a._tgate_reset(a.scene_triggers, tk)
        return []

    def _eval_crm009(self, pair: PairFeature, scene: SceneFeature, now: float) -> List[dict]:
        """CRM-009: Domestic / Intimate Partner Violence — asymmetric force pattern"""
        a = self._a
        tk = f"CRM-009:{pair.pair_key}"

        cond = (
            pair.interaction_active
            and pair.distance < a.DIST_SNATCH * 1.2
            and pair.v_max > a.VEL_RUN * 0.7
            and pair.v_min < a.VEL_WALK * 0.3
            and not pair.same_direction
            and not pair.a.in_checkout
            and not pair.normal_blocked
        )
        _dbg("CRM-009", cond,
             f"d={int(pair.distance)}px v_max={int(pair.v_max)} "
             f"v_min={int(pair.v_min)} same_dir={pair.same_direction}")
        if cond:
            if a._tgate(a.scene_triggers, tk, now, gap_tol=0.5):
                ev = self._fire_rule(
                    "CRM-009", now, "CRIME", "CRITICAL",
                    "Domestic / Intimate Partner Violence",
                    "Asymmetric force: aggressor high-speed, victim near-stationary.",
                    f"d={int(pair.distance)}px aggressor={int(pair.v_max)}px/s victim≈IDLE",
                    "Alert security discreetly. Separate parties. Call police.",
                    ["domestic-violence", "ipv", "asymmetric-force"],
                    "GROUP", 87,
                    extra={"_pair_key": pair.pair_key},
                )
                return [ev] if ev else []
        else:
            a._tgate_reset(a.scene_triggers, tk)
        return []

    def _eval_sec014(self, pair: PairFeature, scene: SceneFeature, now: float) -> List[dict]:
        """SEC-014: Person Confrontation (argument / face-off)"""
        a      = self._a
        tk     = f"SEC-014:{pair.pair_key}"
        d_100  = int(100 * scene.W / 640.0)

        cond = (
            pair.interaction_active
            and pair.distance < d_100
            and pair.v_sum > a.VEL_WALK * 1.5
            and pair.v_sum < a.VEL_RUN * 2.5
            and pair.a.state in ("WALKING", "RUNNING")
            and pair.b.state in ("WALKING", "RUNNING")
        )
        _dbg("SEC-014", cond,
             f"d={int(pair.distance)}px v_sum={int(pair.v_sum)}")
        if cond:
            if a._tgate(a.scene_triggers, tk, now, gap_tol=0.5):
                ev = self._fire_rule(
                    "SEC-014", now, "SECURITY", "HIGH",
                    "Person Confrontation",
                    "Two persons in close aggressive proximity — argument or confrontation.",
                    f"d={int(pair.distance)}px v_sum={int(pair.v_sum)}px/s sustained ≥2.5s",
                    "Dispatch staff to de-escalate. Security standby.",
                    ["confrontation", "argument", "aggressive"],
                    "GROUP", 72,
                    extra={"_pair_key": pair.pair_key},
                )
                return [ev] if ev else []
        else:
            a._tgate_reset(a.scene_triggers, tk)
        return []

    # ══════════════════════════════════════════════════════════════════════════
    # PERSON-LEVEL EVALUATORS
    # ══════════════════════════════════════════════════════════════════════════

    def _eval_crm013(self, person: PersonFeature, now: float) -> Optional[dict]:
        """CRM-013: Surveillance / Pre-Crime Casing"""
        a = self._a
        t = person._track
        cond = (
            person.state in ("IDLE", "STANDING")
            and person.dwell > 45.0
            and person.displacement_5s < a.LOITER_DISP
        )
        _dbg("CRM-013", cond,
             f"state={person.state} dwell={int(person.dwell)}s disp={int(person.displacement_5s)}")
        if cond:
            if a._tgate(t.triggers, "CRM-013", now, gap_tol=5.0):
                return self._fire_rule(
                    "CRM-013", now, "CRIME", "HIGH",
                    "Surveillance / Pre-Crime Casing",
                    "Person stationary near high-value area for extended period.",
                    f"state={person.state} dwell={int(person.dwell)}s",
                    "Approach and engage. Record appearance. Alert security.",
                    ["casing", "surveillance", "pre-crime"],
                    person.uid, 70,
                )
        else:
            a._tgate_reset(t.triggers, "CRM-013")
        return None

    def _eval_crm015(self, person: PersonFeature, now: float) -> Optional[dict]:
        """CRM-015: Fleeing from Scene"""
        a = self._a
        t = person._track
        cond = (
            person.state == "FLEEING"
            and person.velocity >= a.VEL_FLEE
        )
        _dbg("CRM-015", cond, f"state={person.state} vel={int(person.velocity)}")
        if cond:
            if a._tgate(t.triggers, "CRM-015", now, gap_tol=0.5):
                return self._fire_rule(
                    "CRM-015", now, "CRIME", "CRITICAL",
                    "Fleeing from Scene",
                    "Person running at high speed — post-crime escape.",
                    f"state=FLEEING vel={int(person.velocity)}px/s ≥{a.VEL_FLEE}",
                    "Alert exit security. Attempt intercept. Call police.",
                    ["fleeing", "escape", "post-crime"],
                    person.uid, 85,
                )
        else:
            a._tgate_reset(t.triggers, "CRM-015")
        return None

    def _eval_crm016(self, person: PersonFeature, now: float) -> Optional[dict]:
        """CRM-016: Sudden Acceleration / Panic Run"""
        a = self._a
        t = person._track
        prev_state = getattr(t, "_prev_state_re", None)
        cur_state  = person.state
        if prev_state is None:
            t._prev_state_re = cur_state  # type: ignore[attr-defined]
            return None

        cond = (
            prev_state in ("IDLE", "STANDING", "WALKING")
            and cur_state in ("RUNNING", "FLEEING")
            and person.velocity > a.VEL_RUN * 0.8
        )
        _dbg("CRM-016", cond, f"{prev_state}→{cur_state} vel={int(person.velocity)}")
        t._prev_state_re = cur_state  # type: ignore[attr-defined]

        if cond:
            if a._tgate(t.triggers, "CRM-016", now, gap_tol=0.3):
                return self._fire_rule(
                    "CRM-016", now, "CRIME", "HIGH",
                    "Sudden Acceleration / Panic Run",
                    "Person transitioned from calm to running — possible panic or evasion.",
                    f"{prev_state}→{cur_state} vel={int(person.velocity)}px/s",
                    "Investigate cause. Alert security. Review footage.",
                    ["sudden-movement", "panic", "acceleration"],
                    person.uid, 75,
                )
        else:
            a._tgate_reset(t.triggers, "CRM-016")
        return None

    def _eval_sec001(self, person: PersonFeature, now: float) -> Optional[dict]:
        """SEC-001: Loitering"""
        a = self._a
        t = person._track
        cond = (
            person.dwell > 70.0
            and person.displacement_30s < a.LOITER_DISP
            and not person.in_checkout
        )
        _dbg("SEC-001", cond,
             f"dwell={int(person.dwell)}s disp30={int(person.displacement_30s)}")
        if cond:
            if a._tgate(t.triggers, "SEC-001", now, gap_tol=5.0):
                return self._fire_rule(
                    "SEC-001", now, "SECURITY", "MEDIUM",
                    "Loitering Detected",
                    f"Person stationary for {int(person.dwell)}s without checkout.",
                    f"dwell={int(person.dwell)}s disp={int(person.displacement_30s)}px",
                    "Approach and assist or ask them to move.",
                    ["loitering", "dwell", "stationary"],
                    person.uid, 55,
                )
        else:
            a._tgate_reset(t.triggers, "SEC-001")
        return None

    def _eval_sec002(self, person: PersonFeature, now: float) -> Optional[dict]:
        """SEC-002: Rapid Approach / Aggressive Rush"""
        a = self._a
        t = person._track
        cond = (
            person.state in ("RUNNING", "FLEEING")
            and person.velocity >= a.VEL_RUN
            and person.displacement_5s > a.LOITER_DISP * 3
            and not person.in_checkout
        )
        _dbg("SEC-002", cond,
             f"state={person.state} vel={int(person.velocity)} disp5={int(person.displacement_5s)}")
        if cond:
            if a._tgate(t.triggers, "SEC-002", now, gap_tol=0.5):
                return self._fire_rule(
                    "SEC-002", now, "SECURITY", "HIGH",
                    "Rapid Approach / Aggressive Rush",
                    "Person running at high speed through premises.",
                    f"vel={int(person.velocity)}px/s state={person.state} disp={int(person.displacement_5s)}px",
                    "Monitor. Alert security if heading toward exit or staff.",
                    ["rushing", "rapid-approach", "speed"],
                    person.uid, 72,
                )
        else:
            a._tgate_reset(t.triggers, "SEC-002")
        return None

    def _eval_sec003(self, person: PersonFeature, now: float) -> Optional[dict]:
        """SEC-003: After-Hours Restricted Zone Breach — critical severity"""
        a = self._a
        t = person._track
        h = int(time.strftime("%H"))
        after_hours = (h >= 22 or h < 7)
        cond = person.in_restricted and after_hours
        _dbg("SEC-003", cond,
             f"in_restricted={person.in_restricted} after_hours={after_hours} hour={h}")
        if cond:
            if a._tgate(t.triggers, "SEC-003", now, gap_tol=0.5):
                return self._fire_rule(
                    "SEC-003", now, "SECURITY", "CRITICAL",
                    "After-Hours Restricted Zone Breach",
                    "Person in restricted area outside business hours — possible break-in.",
                    f"Restricted zone at {time.strftime('%H:%M')} (outside 07:00–22:00)",
                    "Alert owner and police immediately. Lock all exits.",
                    ["after-hours", "restricted", "break-in", "trespass"],
                    person.uid, 95,
                )
        else:
            a._tgate_reset(t.triggers, "SEC-003")
        return None

    def _eval_sec005(self, person: PersonFeature, now: float) -> Optional[dict]:
        """SEC-005: Restricted Zone Entry"""
        a = self._a
        t = person._track
        cond = person.in_restricted
        _dbg("SEC-005", cond, f"in_restricted={person.in_restricted}")
        if cond:
            if a._tgate(t.triggers, "SEC-005", now, gap_tol=0.5):
                return self._fire_rule(
                    "SEC-005", now, "SECURITY", "HIGH",
                    "Restricted Zone Entry",
                    "Person entered restricted area.",
                    "Person in restricted zone ≥2s",
                    "Alert security. Escort out immediately.",
                    ["restricted-zone", "trespass", "unauthorised"],
                    person.uid, 80,
                )
        else:
            a._tgate_reset(t.triggers, "SEC-005")
        return None

    def _eval_sec006(self, person: PersonFeature, now: float) -> Optional[dict]:
        """SEC-006: Suspicious Repeated Motion / Gesturing near merchandise"""
        a = self._a
        t = person._track
        cond = (
            person.burst_count >= 3
            and person.velocity < a.VEL_WALK * 0.8
            and not person.in_checkout
            and person.dwell > 10.0
            and person.state in ("IDLE", "STANDING")
        )
        _dbg("SEC-006", cond,
             f"bursts={person.burst_count} vel={int(person.velocity)} state={person.state}")
        if cond:
            if a._tgate(t.triggers, "SEC-006", now, gap_tol=1.0):
                return self._fire_rule(
                    "SEC-006", now, "SECURITY", "HIGH",
                    "Suspicious Repeated Motion / Gesturing",
                    "Person making repeated gestures while stationary — possible shoplifting attempt.",
                    f"burst_count={person.burst_count}≥3 vel={int(person.velocity)}px/s dwell={int(person.dwell)}s",
                    "Alert floor staff. Observe merchandise near person.",
                    ["suspicious-gesture", "repeated-motion", "shoplifting"],
                    person.uid, 72,
                )
        else:
            a._tgate_reset(t.triggers, "SEC-006")
        return None

    def _eval_sec008(self, person: PersonFeature, now: float) -> Optional[dict]:
        """SEC-008: Running in Premises"""
        a = self._a
        t = person._track
        cond = (
            person.state in ("RUNNING", "FLEEING")
            and person.velocity >= a.VEL_RUN
        )
        _dbg("SEC-008", cond, f"state={person.state} vel={int(person.velocity)}")
        if cond:
            if a._tgate(t.triggers, "SEC-008", now, gap_tol=0.5):
                return self._fire_rule(
                    "SEC-008", now, "SECURITY", "MEDIUM",
                    "Running in Premises",
                    "Person running at speed — safety concern.",
                    f"state={person.state} vel={int(person.velocity)}px/s",
                    "Alert security to intercept.",
                    ["running", "speed", "safety"],
                    person.uid, 55,
                )
        else:
            a._tgate_reset(t.triggers, "SEC-008")
        return None

    def _eval_beh001(self, person: PersonFeature, now: float) -> Optional[dict]:
        """BEH-001: Nervous / Anxious Behaviour (direction changes + no forward progress)"""
        a = self._a
        t = person._track
        cond = (
            person.direction_changes_30s > 5
            and person.displacement_30s < a.LOITER_DISP * 3
            and a.VEL_WALK * 0.2 < person.velocity < a.VEL_WALK * 1.5
            and person.state not in ("RUNNING", "FLEEING", "FALLEN")
        )
        _dbg("BEH-001", cond,
             f"dir30={person.direction_changes_30s} disp30={int(person.displacement_30s)}")
        if cond:
            if a._tgate(t.triggers, "BEH-001", now, gap_tol=5.0):
                return self._fire_rule(
                    "BEH-001", now, "BEHAVIOR", "MEDIUM",
                    "Nervous / Anxious Behaviour",
                    "High-frequency direction changes with no forward progress.",
                    f"dir_changes={person.direction_changes_30s} net_disp={int(person.displacement_30s)}px",
                    "Observe discretely. Send staff if behaviour persists.",
                    ["nervous", "anxious", "pacing", "pre-crime-indicator"],
                    person.uid, 40,
                )
        else:
            a._tgate_reset(t.triggers, "BEH-001")
        return None

    def _eval_beh003(self, person: PersonFeature, now: float) -> Optional[dict]:
        """BEH-003: Persistent Nervous Circling — circular path with minimal net displacement"""
        a = self._a
        t = person._track
        cond = (
            person.direction_changes_30s > 8
            and person.displacement_30s < a.LOITER_DISP * 5
            and a.VEL_WALK * 0.15 < person.velocity < a.VEL_WALK * 1.3
            and person.state not in ("RUNNING", "FLEEING", "FALLEN")
        )
        _dbg("BEH-003", cond,
             f"dir30={person.direction_changes_30s} disp30={int(person.displacement_30s)}")
        if cond:
            if a._tgate(t.triggers, "BEH-003", now, gap_tol=5.0):
                return self._fire_rule(
                    "BEH-003", now, "BEHAVIOR", "MEDIUM",
                    "Persistent Nervous Circling",
                    "Person making repeated circular movements with minimal net displacement.",
                    f"dir_changes_30s={person.direction_changes_30s}>8 net_disp={int(person.displacement_30s)}px",
                    "Observe discreetly. Dispatch staff to assist.",
                    ["circling", "nervous", "anxious", "agitated"],
                    person.uid, 38,
                )
        else:
            a._tgate_reset(t.triggers, "BEH-003")
        return None

    def _eval_beh010(self, person: PersonFeature, now: float) -> Optional[dict]:
        """BEH-010: Suspicious Look-Around Pattern — slow movement, frequent direction checks"""
        a = self._a
        t = person._track
        cond = (
            person.direction_changes_20s > 4
            and person.state in ("IDLE", "STANDING", "WALKING")
            and person.dwell > 25.0
            and not person.in_checkout
            and person.velocity < a.VEL_WALK * 1.2
            and person.displacement_30s < a.LOITER_DISP * 4
        )
        _dbg("BEH-010", cond,
             f"dir20={person.direction_changes_20s} dwell={int(person.dwell)}s vel={int(person.velocity)}")
        if cond:
            if a._tgate(t.triggers, "BEH-010", now, gap_tol=3.0):
                return self._fire_rule(
                    "BEH-010", now, "BEHAVIOR", "LOW",
                    "Suspicious Look-Around Behaviour",
                    "Person frequently checking surroundings while slow-moving — pre-theft indicator.",
                    f"dir_changes_20s={person.direction_changes_20s} dwell={int(person.dwell)}s",
                    "Observe. Staff nearby reduces opportunistic theft.",
                    ["look-around", "suspicious", "evasive", "pre-crime-indicator"],
                    person.uid, 32,
                )
        else:
            a._tgate_reset(t.triggers, "BEH-010")
        return None

    def _eval_beh012(self, person: PersonFeature, now: float) -> Optional[dict]:
        """BEH-012: Pacing / Agitated Repetitive Movement"""
        a = self._a
        t = person._track
        cond = (
            person.direction_changes_20s > 4
            and person.displacement_5s < a.LOITER_DISP * 2
            and a.VEL_WALK * 0.15 < person.velocity < a.VEL_WALK * 1.3
        )
        _dbg("BEH-012", cond,
             f"dir20={person.direction_changes_20s} disp5={int(person.displacement_5s)}")
        if cond:
            if a._tgate(t.triggers, "BEH-012", now, gap_tol=3.0):
                return self._fire_rule(
                    "BEH-012", now, "BEHAVIOR", "MEDIUM",
                    "Pacing / Agitated Repetitive Movement",
                    "Repeated directional changes with no net movement.",
                    f"dir_changes_20s={person.direction_changes_20s} displacement low",
                    "Observe. Dispatch staff if agitated.",
                    ["pacing", "agitated", "repetitive-movement"],
                    person.uid, 38,
                )
        else:
            a._tgate_reset(t.triggers, "BEH-012")
        return None

    def _eval_beh017(self, person: PersonFeature, now: float) -> Optional[dict]:
        """BEH-017: Erratic Unpredictable Movement (isolated — not in interaction)"""
        a = self._a
        t = person._track
        cond = (
            person.direction_changes_15s > 8
            and person.state not in ("FALLEN",)
            and not a._in_any_interaction(t, time.time())
        )
        _dbg("BEH-017", cond, f"dir15={person.direction_changes_15s}")
        if cond:
            if a._tgate(t.triggers, "BEH-017", now, gap_tol=2.0):
                return self._fire_rule(
                    "BEH-017", now, "BEHAVIOR", "MEDIUM",
                    "Erratic Unpredictable Movement",
                    "Person moving in highly erratic patterns — isolated from others.",
                    f"dir_changes_15s={person.direction_changes_15s} no interaction",
                    "Alert security. Possible medical episode or threat behaviour.",
                    ["erratic", "unpredictable", "anomalous-gait"],
                    person.uid, 42,
                )
        else:
            a._tgate_reset(t.triggers, "BEH-017")
        return None

    def _eval_beh018(self, person: PersonFeature, now: float) -> Optional[dict]:
        """BEH-018: Medical Distress — Sudden Fall after mobile state"""
        a = self._a
        t = person._track
        prev_beh  = getattr(t, "_prev_beh_state_re", None)
        cur_state = person.state
        if prev_beh is None:
            t._prev_beh_state_re = cur_state  # type: ignore[attr-defined]
            return None

        cond = (
            cur_state == "FALLEN"
            and prev_beh in ("WALKING", "RUNNING", "STANDING")
        )
        _dbg("BEH-018", cond, f"{prev_beh}→{cur_state}")
        t._prev_beh_state_re = cur_state  # type: ignore[attr-defined]

        if cond:
            if a._tgate(t.triggers, "BEH-018", now, gap_tol=1.0):
                return self._fire_rule(
                    "BEH-018", now, "BEHAVIOR", "CRITICAL",
                    "Apparent Medical Distress — Sudden Fall",
                    "Person collapsed after walking/running — possible cardiac event.",
                    f"State transition {prev_beh}→FALLEN",
                    "Call emergency services immediately. First aid on scene.",
                    ["medical", "collapse", "fall", "emergency"],
                    person.uid, 90,
                )
        else:
            a._tgate_reset(t.triggers, "BEH-018")
        return None

    def _eval_beh022(self, person: PersonFeature, now: float) -> Optional[dict]:
        """BEH-022: Person Sleeping / Unconscious (FALLEN > 3 min)"""
        a = self._a
        t = person._track
        cond = person.state == "FALLEN" and person.dwell > 180.0
        _dbg("BEH-022", cond, f"dwell={int(person.dwell)}s")
        if cond:
            if a._tgate(t.triggers, "BEH-022", now, gap_tol=10.0):
                return self._fire_rule(
                    "BEH-022", now, "BEHAVIOR", "LOW",
                    "Person Sleeping / Unconscious",
                    f"Person horizontal and stationary for {int(person.dwell)}s.",
                    f"FALLEN >{int(person.dwell)}s",
                    "Approach and check well-being. Alert security.",
                    ["sleeping", "unconscious", "welfare-check"],
                    person.uid, 22,
                )
        else:
            a._tgate_reset(t.triggers, "BEH-022")
        return None

    def _eval_beh027(self, person: PersonFeature, now: float) -> Optional[dict]:
        """BEH-027: Persistent Dwell Near High-Value / Restricted Area (> 2 min)"""
        a = self._a
        t = person._track
        cond = person.in_restricted and person.dwell > 120.0
        _dbg("BEH-027", cond, f"in_res={person.in_restricted} dwell={int(person.dwell)}s")
        if cond:
            if a._tgate(t.triggers, "BEH-027", now, gap_tol=5.0):
                return self._fire_rule(
                    "BEH-027", now, "BEHAVIOR", "HIGH",
                    "Persistent Dwell Near High-Value Area",
                    f"Person in restricted zone for {int(person.dwell)}s.",
                    f"Restricted zone dwell={int(person.dwell)}s > 120s",
                    "Alert floor security. Approach with assistance pretext.",
                    ["high-value", "dwell", "shoplifting-risk"],
                    person.uid, 58,
                )
        else:
            a._tgate_reset(t.triggers, "BEH-027")
        return None

    def _eval_biz003(self, person: PersonFeature, now: float) -> Optional[dict]:
        """BIZ-003: High Product Engagement (customer at display)"""
        a = self._a
        t = person._track
        cond = (
            person.state in ("STANDING", "IDLE")
            and person.dwell > 60.0
            and person.displacement_5s < a.LOITER_DISP * 1.5
            and not person.in_checkout
        )
        _dbg("BIZ-003", cond, f"dwell={int(person.dwell)}s state={person.state}")
        if cond:
            if a._tgate(t.triggers, "BIZ-003", now, gap_tol=5.0):
                return self._fire_rule(
                    "BIZ-003", now, "BUSINESS", "LOW",
                    "High Product Engagement",
                    f"Customer at display for {int(person.dwell)}s.",
                    f"dwell={int(person.dwell)}s stationary near display",
                    "Alert staff to assist — conversion opportunity.",
                    ["product-dwell", "engagement", "conversion"],
                    person.uid, 30,
                )
        else:
            a._tgate_reset(t.triggers, "BIZ-003")
        return None

    def _eval_crw004(self, person: PersonFeature, now: float) -> Optional[dict]:
        """CRW-004: Person on Ground / Fall Detected"""
        a = self._a
        t = person._track
        cond = person.state == "FALLEN" and person.dwell > 1.5
        _dbg("CRW-004", cond, f"state={person.state} dwell={person.dwell:.1f}s")
        if cond:
            if a._tgate(t.triggers, "CRW-004", now, gap_tol=0.5):
                return self._fire_rule(
                    "CRW-004", now, "CROWD", "CRITICAL",
                    "Person on Ground / Fall Detected",
                    "Person appears to have fallen — possible injury or emergency.",
                    f"state=FALLEN dwell={int(person.dwell)}s",
                    "Alert first aid. Clear area. Call emergency services if needed.",
                    ["fallen", "collapse", "medical", "emergency"],
                    person.uid, 90,
                )
        else:
            a._tgate_reset(t.triggers, "CRW-004")
        return None

    # ══════════════════════════════════════════════════════════════════════════
    # SCENE-LEVEL EVALUATORS
    # ══════════════════════════════════════════════════════════════════════════

    def _eval_crm010(self, scene: SceneFeature, now: float) -> Optional[dict]:
        """CRM-010: Distraction Theft Setup — stationary person in restricted + mobile cover"""
        a = self._a
        if scene.count < 3:
            a._tgate_reset(a.scene_triggers, "CRM-010")
            return None

        stat_restricted = [
            p for p in scene.persons
            if p.in_restricted and p.state in ("IDLE", "STANDING")
        ]
        mobile_others = [
            p for p in scene.persons
            if p.state in ("WALKING", "RUNNING") and not p.in_restricted
        ]

        cond = len(stat_restricted) >= 1 and len(mobile_others) >= 2
        _dbg("CRM-010", cond,
             f"stat_restricted={len(stat_restricted)} mobile_cover={len(mobile_others)}")
        if cond:
            if a._tgate(a.scene_triggers, "CRM-010", now, gap_tol=1.0):
                return self._fire_rule(
                    "CRM-010", now, "CRIME", "HIGH",
                    "Distraction Theft Setup",
                    "Person stationary near restricted area while others provide mobile cover.",
                    f"{len(stat_restricted)} in restricted zone, {len(mobile_others)} mobile cover",
                    "Alert all staff. Approach stationary person with assistance pretext.",
                    ["distraction-theft", "coordinated", "setup"],
                    "GROUP", 76,
                )
        else:
            a._tgate_reset(a.scene_triggers, "CRM-010")
        return None

    def _eval_crm011(self, scene: SceneFeature, now: float) -> Optional[dict]:
        """CRM-011: Group Fight / Brawl (3+ running in tight cluster)"""
        a = self._a
        if scene.count < 3:
            a._tgate_reset(a.scene_triggers, "CRM-011")
            return None
        running = [pf._track for pf in scene.persons
                   if pf.state in ("RUNNING", "FLEEING")]
        if len(running) < 3:
            a._tgate_reset(a.scene_triggers, "CRM-011")
            _dbg("CRM-011", False, f"running={len(running)}<3")
            return None
        positions = [t.last_pos() for t in running]
        xs, ys = zip(*positions)
        spread = float(max(max(xs) - min(xs), max(ys) - min(ys)))
        cond = spread < a.DIST_CROWD
        _dbg("CRM-011", cond, f"running={len(running)} spread={int(spread)}px")
        if cond:
            if a._tgate(a.scene_triggers, "CRM-011", now, gap_tol=0.5):
                return self._fire_rule(
                    "CRM-011", now, "CRIME", "CRITICAL",
                    "Group Fight / Brawl",
                    f"{len(running)} persons in tight cluster all running.",
                    f"{len(running)} RUNNING within {int(spread)}px",
                    "Call police immediately. Alert all security. Clear bystanders.",
                    ["fight", "brawl", "group-fight", "violence"],
                    "GROUP", 88,
                )
        else:
            a._tgate_reset(a.scene_triggers, "CRM-011")
        return None

    def _eval_crm014(self, scene: SceneFeature, now: float) -> Optional[dict]:
        """CRM-014: Mob Formation / Group Aggression (3+ mobile, fast)"""
        a = self._a
        if scene.mobile_count < 3:
            a._tgate_reset(a.scene_triggers, "CRM-014")
            return None
        cond = scene.avg_velocity > a.VEL_RUN * 0.7
        _dbg("CRM-014", cond, f"mobile={scene.mobile_count} avg_vel={int(scene.avg_velocity)}")
        if cond:
            if a._tgate(a.scene_triggers, "CRM-014", now, gap_tol=0.5):
                return self._fire_rule(
                    "CRM-014", now, "CRIME", "CRITICAL",
                    "Mob Formation / Group Aggression",
                    f"{scene.mobile_count} persons moving rapidly together.",
                    f"avg_vel={int(scene.avg_velocity)}px/s {scene.mobile_count} mobile",
                    "Alert all security. Call police.",
                    ["mob", "gang", "group-aggression"],
                    "GROUP", 82,
                )
        else:
            a._tgate_reset(a.scene_triggers, "CRM-014")
        return None

    def _eval_crw001(self, scene: SceneFeature, now: float) -> Optional[dict]:
        """CRW-001: Crowd Density Critical (≥5 persons)"""
        a = self._a
        cond = scene.count >= 5
        _dbg("CRW-001", cond, f"count={scene.count}")
        if cond:
            if a._tgate(a.scene_triggers, "CRW-001", now, gap_tol=1.0):
                return self._fire_rule(
                    "CRW-001", now, "CROWD", "CRITICAL",
                    "Crowd Density Critical",
                    f"{scene.count} persons in frame ≥4s.",
                    f"{scene.count} ≥ 5 persons",
                    "Restrict entry. Notify fire safety officer.",
                    ["crowd", "density", "occupancy"],
                    "GROUP", 82,
                )
        else:
            a._tgate_reset(a.scene_triggers, "CRW-001")
        return None

    def _eval_sec009(self, scene: SceneFeature, now: float) -> Optional[dict]:
        """SEC-009: After-Hours Motion Detected"""
        a = self._a
        cond = scene.count > 0 and scene.after_hours
        _dbg("SEC-009", cond, f"count={scene.count} after_hours={scene.after_hours}")
        if cond:
            if a._tgate(a.scene_triggers, "SEC-009", now, gap_tol=1.0):
                return self._fire_rule(
                    "SEC-009", now, "SECURITY", "CRITICAL",
                    "After-Hours Motion Detected",
                    "Person(s) detected outside operational hours — possible break-in.",
                    f"Motion at {time.strftime('%H:%M')} outside 07:00–22:00",
                    "Alert owner and security immediately. Consider calling police.",
                    ["after-hours", "break-in", "burglary"],
                    "GROUP", 94,
                )
        else:
            a._tgate_reset(a.scene_triggers, "SEC-009")
        return None

    def _eval_sec011(self, scene: SceneFeature, now: float) -> Optional[dict]:
        """SEC-011: Coordinated Group — Possible Distraction (3-6 tight cluster not at checkout)"""
        a = self._a
        if not (3 <= scene.count <= 6):
            a._tgate_reset(a.scene_triggers, "SEC-011")
            return None
        non_chk = [pf for pf in scene.persons if not pf.in_checkout]
        if len(non_chk) < 3:
            a._tgate_reset(a.scene_triggers, "SEC-011")
            return None
        xs = [pf.last_x for pf in non_chk]
        ys = [pf.last_y for pf in non_chk]
        spread  = float(max(max(xs) - min(xs), max(ys) - min(ys)))
        thr_70  = int(70 * scene.W / 640.0)
        cond    = spread < thr_70
        _dbg("SEC-011", cond, f"non_chk={len(non_chk)} spread={int(spread)}px")
        if cond:
            if a._tgate(a.scene_triggers, "SEC-011", now, gap_tol=1.0):
                return self._fire_rule(
                    "SEC-011", now, "SECURITY", "HIGH",
                    "Coordinated Group — Possible Distraction",
                    "Tight cluster of 3+ persons near merchandise area.",
                    f"{len(non_chk)} persons within {thr_70}px cluster",
                    "Alert all staff. Secure high-value areas.",
                    ["group", "coordinated", "distraction"],
                    "GROUP", 78,
                )
        else:
            a._tgate_reset(a.scene_triggers, "SEC-011")
        return None

    def _eval_sec012(self, scene: SceneFeature, now: float) -> Optional[dict]:
        """SEC-012: Perimeter Encroachment — persons lingering at frame boundary"""
        a = self._a
        margin_x = int(scene.W * 0.08)
        margin_y = int(scene.H * 0.08)
        edge_persons = [
            p for p in scene.persons
            if (p.last_x < margin_x or p.last_x > scene.W - margin_x
                or p.last_y > scene.H - margin_y)
            and p.dwell > 30.0
            and p.state in ("IDLE", "STANDING", "WALKING")
        ]
        cond = len(edge_persons) >= 1
        _dbg("SEC-012", cond, f"edge_persons={len(edge_persons)}")
        if cond:
            if a._tgate(a.scene_triggers, "SEC-012", now, gap_tol=3.0):
                return self._fire_rule(
                    "SEC-012", now, "SECURITY", "MEDIUM",
                    "Perimeter Encroachment",
                    "Person(s) loitering near premises boundary.",
                    f"{len(edge_persons)} person(s) near boundary ≥30s",
                    "Monitor and verify. Alert security if pattern persists.",
                    ["perimeter", "boundary", "encroachment"],
                    "GROUP", 52,
                )
        else:
            a._tgate_reset(a.scene_triggers, "SEC-012")
        return None

    def _eval_beh026(self, scene: SceneFeature, now: float) -> Optional[dict]:
        """BEH-026: Group Standing Block — Deliberate Obstruction (3+ stationary tight cluster)"""
        a = self._a
        stationary = [pf for pf in scene.persons if pf.state in ("IDLE", "STANDING")]
        if len(stationary) < 3:
            a._tgate_reset(a.scene_triggers, "BEH-026")
            return None
        xs     = [pf.last_x for pf in stationary]
        ys     = [pf.last_y for pf in stationary]
        spread = float(max(max(xs) - min(xs), max(ys) - min(ys)))
        thr_80 = int(80 * scene.W / 640.0)
        cond   = spread < thr_80
        _dbg("BEH-026", cond, f"stationary={len(stationary)} spread={int(spread)}px")
        if cond:
            if a._tgate(a.scene_triggers, "BEH-026", now, gap_tol=2.0):
                return self._fire_rule(
                    "BEH-026", now, "BEHAVIOR", "MEDIUM",
                    "Group Standing Block — Deliberate Obstruction",
                    "Tight cluster of 3+ stationary persons blocking area.",
                    f"{len(stationary)} stationary within {thr_80}px cluster",
                    "Dispatch staff to politely redirect group.",
                    ["obstruction", "group-standing", "aisle-block"],
                    "GROUP", 38,
                )
        else:
            a._tgate_reset(a.scene_triggers, "BEH-026")
        return None

    def _eval_biz004(self, scene: SceneFeature, now: float) -> Optional[dict]:
        """BIZ-004: Queue Length Exceeded (≥3 persons at checkout)"""
        a      = self._a
        in_chk = [pf for pf in scene.persons if pf.in_checkout]
        cond   = len(in_chk) >= 3
        _dbg("BIZ-004", cond, f"in_checkout={len(in_chk)}")
        if cond:
            if a._tgate(a.scene_triggers, "BIZ-004", now, gap_tol=2.0):
                return self._fire_rule(
                    "BIZ-004", now, "BUSINESS", "MEDIUM",
                    "Queue Length Exceeded",
                    f"Checkout queue: {len(in_chk)} persons.",
                    "≥3 persons in checkout zone",
                    "Open additional checkout. Alert floor manager.",
                    ["queue", "checkout", "wait-time"],
                    "GROUP", 25,
                )
        else:
            a._tgate_reset(a.scene_triggers, "BIZ-004")
        return None
